<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCTV Breadcrumb</name>
   <tag></tag>
   <elementGuidId>8206b4ad-5540-48bc-b64b-6a3b5624d56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbarBlur']/div/nav/ol/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9e45a58-f5c3-4fcf-bca8-8913fc063267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opacity-5 text-dark</value>
      <webElementGuid>804e7f48-5452-418f-b1e5-c7a605a1392f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cctv/detail/64fea065acbef66fd5476494</value>
      <webElementGuid>b9cbc282-0539-4c23-9864-bc49e7364639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CCTV</value>
      <webElementGuid>ac3dd422-a0b0-436f-97de-32438f3c2089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarBlur&quot;)/div[@class=&quot;container-fluid py-1 px-3&quot;]/nav[1]/ol[@class=&quot;breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5&quot;]/li[@class=&quot;breadcrumb-item text-sm&quot;]/a[@class=&quot;opacity-5 text-dark&quot;]</value>
      <webElementGuid>ecd75199-958f-4e9b-b50c-07ea2c2633f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbarBlur']/div/nav/ol/li[3]/a</value>
      <webElementGuid>0073693a-8fa1-46d0-9937-51ec24fa4c52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CCTV')]</value>
      <webElementGuid>b4ed3118-e1bf-4ce5-87d9-7d502fa08276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/cctv/detail/64fea065acbef66fd5476494')]</value>
      <webElementGuid>7e2083c5-e3e7-4aa2-9c68-c42cf5ee98f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>41bafe14-aa36-4827-bf0a-1c006973ee2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cctv/detail/64fea065acbef66fd5476494' and (text() = 'CCTV' or . = 'CCTV')]</value>
      <webElementGuid>7f8a8ff6-d5ca-4a74-a4be-0a08fe81e087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
