<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data Entries Information</name>
   <tag></tag>
   <elementGuidId>df6c3a0b-ddb1-467c-88d2-f9870c4183d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='table_data_info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#table_data_info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d17e1205-2bbc-405a-b346-0b9aaf436c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>24dc634d-0c78-49fd-9f20-95d0024f1dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>table_data_info</value>
      <webElementGuid>f6ae1119-260f-4a4c-9b53-8e730666119e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>e41b48d7-e514-458b-ba30-c67d4742b84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>616fa6df-4c89-4bb7-8ead-c0c634f1c62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 33 of 33 entries</value>
      <webElementGuid>8869345d-e156-4211-acbf-07c1973dd1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_data_info&quot;)</value>
      <webElementGuid>7aab95ab-d408-498c-9e6d-cba4a325aee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='table_data_info']</value>
      <webElementGuid>039bf6a4-8fde-4186-9fe5-08c14172b0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div</value>
      <webElementGuid>2b670f8a-d86e-4165-92c1-6640d525a70c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'table_data_info' and (text() = 'Showing 1 to 33 of 33 entries' or . = 'Showing 1 to 33 of 33 entries')]</value>
      <webElementGuid>1cb216d5-60cb-4ba4-a5a1-49627307e033</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
