<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stadium Breadcrumb</name>
   <tag></tag>
   <elementGuidId>7f4a1b39-45e9-41dd-95f8-58ee98113b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='navbarBlur']/div/nav/ol/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0520845-e3a7-4e21-a5bc-4fe67e324606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>opacity-5 text-dark</value>
      <webElementGuid>0d21e5e9-b960-40b1-bcea-86e32f91a11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/cctv/stadion</value>
      <webElementGuid>f3c3a82a-1764-4b4b-a025-a8cb253e2e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stadium</value>
      <webElementGuid>5c9394c9-9016-4daa-adde-dd79236d99d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarBlur&quot;)/div[@class=&quot;container-fluid py-1 px-3&quot;]/nav[1]/ol[@class=&quot;breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0 me-sm-6 me-5&quot;]/li[@class=&quot;breadcrumb-item text-sm&quot;]/a[@class=&quot;opacity-5 text-dark&quot;]</value>
      <webElementGuid>42a09734-4912-4127-a90b-7cacc6f84c91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='navbarBlur']/div/nav/ol/li[2]/a</value>
      <webElementGuid>a84fd74c-1c52-4717-b7a7-00746380ef9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Stadium')]</value>
      <webElementGuid>5fbdeff9-061e-427c-8531-a71f05deb8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/cctv/stadion')])[2]</value>
      <webElementGuid>8669dd57-f535-43fb-b6f8-97a93769cb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li[2]/a</value>
      <webElementGuid>b905bea8-9b22-4489-8e8c-73193199abaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/cctv/stadion' and (text() = 'Stadium' or . = 'Stadium')]</value>
      <webElementGuid>815cde54-5277-438c-ac6f-f7dafcb7d177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
