<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_RTSP_rtsp</name>
   <tag></tag>
   <elementGuidId>d3f2c3d5-1fbd-449b-beae-3ea40f7640ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rtsp']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @id = 'rtsp' and @name = 'rtsp' and @placeholder = 'RTSP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#rtsp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d8e35e0-b5c0-47ad-ac93-ba7c17e7f2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81a610b3-ac20-48cc-8db0-0ff6298dbfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>aaab7b92-ba18-44c0-a47f-c0112d8bb32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rtsp</value>
      <webElementGuid>36c3dea4-8efb-4577-a7fe-9b0529d53daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rtsp</value>
      <webElementGuid>3e9065cb-9364-4f15-9dce-e62957019d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RTSP</value>
      <webElementGuid>ddabd358-d9b7-482c-a69f-8d7322af6813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rtsp&quot;)</value>
      <webElementGuid>ced976bb-dd96-4a86-85eb-0e5d941050a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rtsp']</value>
      <webElementGuid>19e780f6-d12e-4949-bd13-46ebc447edff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3003c7cf-3553-4385-8a04-86a2a31d7e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'rtsp' and @name = 'rtsp' and @placeholder = 'RTSP']</value>
      <webElementGuid>7a4d59a3-e5e3-421b-aa86-4b4690cc4dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
