<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CCTV ID_cctv_id</name>
   <tag></tag>
   <elementGuidId>a6f86238-e542-48c7-ac4d-c7ffab18ad84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cctv_id']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @id = 'cctv_id' and @name = 'cctv_id' and @placeholder = 'CCTV ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cctv_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>200faa07-b261-45b5-a2a6-37dd6b60cb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e374a66a-c366-4127-8861-6f1a27ec4911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>9c1bb8ad-9549-4daa-9ef0-3903723713f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cctv_id</value>
      <webElementGuid>53d9e3c4-0783-48d3-9106-5b9ea1402acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cctv_id</value>
      <webElementGuid>486ef327-fb01-460d-995c-daceb0964f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CCTV ID</value>
      <webElementGuid>06edb86f-4936-4b13-bcf6-f10736f1b6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cctv_id&quot;)</value>
      <webElementGuid>59b22c29-9d0d-40f6-ad6b-7d25e8cc6238</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cctv_id']</value>
      <webElementGuid>ee99500e-f3fb-41cf-8633-2d37ab5fb378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>85537e15-f77a-4862-ab54-490468f0675b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'cctv_id' and @name = 'cctv_id' and @placeholder = 'CCTV ID']</value>
      <webElementGuid>ba53097e-dc96-4308-9552-c1acc4696dee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
