<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_svg-inline--fa fa-eye</name>
   <tag></tag>
   <elementGuidId>527f060b-63e1-48a1-9e92-17c7f239490d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;table_data&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;d-flex justify-content-center&quot;]/a[@class=&quot;btn btn-action btn-action--detail&quot;]/svg[@class=&quot;svg-inline--fa fa-eye&quot;][count(. | //svg[@class = 'svg-inline--fa fa-eye' and @aria-hidden = 'true' and @focusable = 'false' and @data-prefix = 'fas' and @data-icon = 'eye' and @role = 'img' and @xmlns = 'http://www.w3.org/2000/svg' and @viewBox = '0 0 576 512']) = count(//svg[@class = 'svg-inline--fa fa-eye' and @aria-hidden = 'true' and @focusable = 'false' and @data-prefix = 'fas' and @data-icon = 'eye' and @role = 'img' and @xmlns = 'http://www.w3.org/2000/svg' and @viewBox = '0 0 576 512'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline--fa.fa-eye</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>504461d3-6c3a-4146-9c0a-472e56980a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-eye</value>
      <webElementGuid>a07ab723-a254-4284-8044-82044d27ed4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5801a232-f7d2-4b81-9d37-ca11a4d396aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>16fb1a07-ce8a-4166-86a0-db8eb546d57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>1696e6c5-9ffd-403d-a436-06cd3fdb1550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>eye</value>
      <webElementGuid>eb6accbe-89af-4e28-82f8-4ad5fe834e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>efb3f88b-1dae-473f-a855-ec44492b3083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>c2131a5a-b1f5-45a1-b6a0-00e5191799e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 576 512</value>
      <webElementGuid>5c547e87-3c84-4d12-92f4-82690b183e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table_data&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;d-flex justify-content-center&quot;]/a[@class=&quot;btn btn-action btn-action--detail&quot;]/svg[@class=&quot;svg-inline--fa fa-eye&quot;]</value>
      <webElementGuid>c6f4ded3-e654-4bf9-b9c4-f1d4a6d92ae9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
