<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CCTV Search Box</name>
   <tag></tag>
   <elementGuidId>5a15eb15-c1f6-41ae-af0c-aaf42c302a89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.select2-dropdown.select2-dropdown--below</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>da7dacf8-4aaf-4d4d-bd01-1014025ca8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-dropdown select2-dropdown--below</value>
      <webElementGuid>1e43bf9c-0ff5-4af1-b726-50ed69a60824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>d8e5cf2e-cd32-4607-9cc6-0fa7012ad8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing 1CCTV 1</value>
      <webElementGuid>0db2f1a4-db42-483a-8616-3a901be1be8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[@class=&quot;g-sidenav-show  bg-gray-100&quot;]/span[@class=&quot;select2-container select2-container--default select2-container--open&quot;]/span[@class=&quot;select2-dropdown select2-dropdown--below&quot;]</value>
      <webElementGuid>ceb27055-cc01-4ee1-a35c-5a0c29297a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/span/span</value>
      <webElementGuid>1fba841d-19fd-4236-b981-1ab289020040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Testing 1CCTV 1' or . = 'Testing 1CCTV 1')]</value>
      <webElementGuid>6541da32-61ad-4ce4-8df9-8dab8d34f34d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
