<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stadium Search Box</name>
   <tag></tag>
   <elementGuidId>88116e11-bbf4-42cb-a69e-f990a3d7ba19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-stadion-results']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-stadion-results</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>2411665c-3665-4edb-963e-01b6e416a844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
      <webElementGuid>28db3192-3049-456f-9dba-f4b3d00e3f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>c9727ecd-fa35-4a48-bc53-724f63d53b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-stadion-results</value>
      <webElementGuid>1cc544a7-c995-4bcd-bf92-4afbe4d4abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9287572e-9712-4e46-ae48-55849962c66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ab11b7c-6c5c-48ba-9c11-052779abd195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stadion Utama Gelora Bung KarnoStadion Madya Gelora Bung KarnoIndomilk Arena StadiumStadion PatriotStadion Si Jalak HarupatStadion Gelora Bandung Lautan ApiStadion ManahanStadion Maguwoharjo SlemanStadion Gelora Bung TomoStadion Gelora Bangkalan</value>
      <webElementGuid>8bb5fab1-edde-4141-b6de-f001bf27215f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-stadion-results&quot;)</value>
      <webElementGuid>91664887-1f3c-4b60-8f9a-9b6b80d443da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//ul[@id='select2-stadion-results']</value>
      <webElementGuid>7b67664d-c3a4-4be0-9c9b-1baf6b502db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul</value>
      <webElementGuid>c47fce0f-f759-4d3a-b96c-65a3a74b506f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[@id = 'select2-stadion-results' and (text() = 'Stadion Utama Gelora Bung KarnoStadion Madya Gelora Bung KarnoIndomilk Arena StadiumStadion PatriotStadion Si Jalak HarupatStadion Gelora Bandung Lautan ApiStadion ManahanStadion Maguwoharjo SlemanStadion Gelora Bung TomoStadion Gelora Bangkalan' or . = 'Stadion Utama Gelora Bung KarnoStadion Madya Gelora Bung KarnoIndomilk Arena StadiumStadion PatriotStadion Si Jalak HarupatStadion Gelora Bandung Lautan ApiStadion ManahanStadion Maguwoharjo SlemanStadion Gelora Bung TomoStadion Gelora Bangkalan')]</value>
      <webElementGuid>656f9c37-4041-4b04-b75b-ab4527cd31f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
