<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Stadium Selection Bar</name>
   <tag></tag>
   <elementGuidId>ba9004bd-af40-44ed-965f-0798b1a7b4b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-stadion-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-stadion-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5a72ce17-ddbd-49d0-be71-147009feabf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>4605fd1f-e43c-44f4-861e-5b17c6b3ab48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-stadion-container</value>
      <webElementGuid>dc083e3f-e96d-4e6d-857f-65a1009eed1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>ebde42c3-3217-43ee-ac31-4ffb87d58b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>992b71de-2016-47d2-b290-992451605da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Search Stadium --</value>
      <webElementGuid>925b0c45-9144-4be6-a811-4bb729bf2edc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Search Stadium --</value>
      <webElementGuid>d4213f9a-a8ed-4cfd-b4ea-baeddcb8e151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-stadion-container&quot;)</value>
      <webElementGuid>90658e66-7390-4cbb-bc4c-418f55480849</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-stadion-container']</value>
      <webElementGuid>245c99cc-74c4-46dc-942a-9538511b5d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>8102ef3c-1cc0-4f6e-a800-1b47573d7f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-stadion-container' and @title = '-- Search Stadium --' and (text() = '-- Search Stadium --' or . = '-- Search Stadium --')]</value>
      <webElementGuid>996970bb-9a5c-4c95-95ba-ac0d637df2e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
