<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Video</name>
   <tag></tag>
   <elementGuidId>c59a0079-c52b-4cf2-ac0f-4fd7b1ebbba2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//video[@id='videoPlayback_html5_api']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#videoPlayback_html5_api</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>video</value>
      <webElementGuid>5ee47ea0-ee96-4125-a50a-3696cd9692bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>videoPlayback_html5_api</value>
      <webElementGuid>726d2839-1a75-4370-9c4b-52a418038abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-tech</value>
      <webElementGuid>f44c3b66-a37b-4ad7-b06c-7bba98fdf9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>904d79cf-55b0-4ff4-8815-c0908c3ec2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-setup</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>78b370d9-9141-4f9f-a734-94300b15d7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>muted</name>
      <type>Main</type>
      <value>muted</value>
      <webElementGuid>98149b4e-ad66-43ca-8ad6-5e342db63457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>2da1af27-6bea-4fff-ba2d-42d668081fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>9fc42ff7-2ab4-43ee-83ba-155ce2468fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>application</value>
      <webElementGuid>2fdc5b6d-ad47-476e-bed2-275fbe120c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/playback_video/stream?id=65273c11a21542f9826f23a6&amp;filename=2024-01-08T12-26-38.mp4&amp;url=http://192.168.229.11:9000/api/v1/recording/stadium/2024-01-08T12-26-38.mp4</value>
      <webElementGuid>94dca55d-3776-4a38-b94f-fe12efba02b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;videoPlayback_html5_api&quot;)</value>
      <webElementGuid>8952ca34-0d1e-4036-bd39-5b3fa949b5e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//video[@id='videoPlayback_html5_api']</value>
      <webElementGuid>0b4bdaac-bb7b-4227-986f-b020bf2a9a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='videoPlayback']/video</value>
      <webElementGuid>7466608e-e164-48de-95aa-2031e3641808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//video</value>
      <webElementGuid>1742c365-2a94-4f61-88aa-a30d1a3a9e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//video[@id = 'videoPlayback_html5_api' and @src = '/playback_video/stream?id=65273c11a21542f9826f23a6&amp;filename=2024-01-08T12-26-38.mp4&amp;url=http://192.168.229.11:9000/api/v1/recording/stadium/2024-01-08T12-26-38.mp4']</value>
      <webElementGuid>54a2b50c-9f76-409f-bba3-56ce3fa80c50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
