<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bottom Search Identity</name>
   <tag></tag>
   <elementGuidId>0fd88e00-b1a0-45cb-9272-dcec90808ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='snapshotIdentify_primary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snapshotIdentify_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fadb24cf-f400-4664-aa33-2245fd992c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29ea3b27-62a1-4013-a77e-498b55947792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snapshotIdentify_primary</value>
      <webElementGuid>4e432251-4dcd-418e-a7db-1cc63357f93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>a814f861-b351-4ec6-8b9a-83a1e3980a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>010e010b-2af2-417d-83b7-e872c2b02338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>e0a9adc5-b974-43d0-88c1-bed065b9e42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Identity</value>
      <webElementGuid>9c6170b0-f33c-461d-b96a-1dc3e1d67910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snapshotIdentify_primary&quot;)</value>
      <webElementGuid>fa424e0e-211a-4bfe-915c-db00df108d51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='snapshotIdentify_primary']</value>
      <webElementGuid>4144c0ec-d76d-468e-8448-c9f2fbbe8ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>21f9a6f3-38d2-49d5-b926-b80e0a59aef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'snapshotIdentify_primary' and (text() = 'Search Identity' or . = 'Search Identity')]</value>
      <webElementGuid>a744310e-4171-4149-9b5b-9c9a7a0ef734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
