<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bottom Loading CCTV Stream</name>
   <tag></tag>
   <elementGuidId>88035ea0-9ef1-4084-a57c-555909d586df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stream_primary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream_primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>9617aff4-f0a9-44bf-b843-793e5b85aa1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream_primary</value>
      <webElementGuid>6c24d2a1-c74a-4f68-b9e2-39985a7a4152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream_primary&quot;)</value>
      <webElementGuid>151b39de-e237-41bc-aa7d-ea42f393ac57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stream_primary']</value>
      <webElementGuid>bcc8e14b-9aab-4da0-a3f5-6047f1c51649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_stream_primary']/canvas</value>
      <webElementGuid>0954c5a0-f139-403b-8b77-644fff4002bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>4aa6a99d-b8f2-4b98-b3d7-aea9955ba8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stream_primary']</value>
      <webElementGuid>93ec01ca-115d-40f8-bbee-11130b2bbeb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
