<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Bottom Camera Selection</name>
   <tag></tag>
   <elementGuidId>98cdd6dd-314e-4458-bfed-a4a438fede93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-select_camera_primary-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-select_camera_primary-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7c69ed5a-9c65-48c3-89eb-954c2c67dccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>7710668a-0ee3-40b7-882e-77f7ca31cb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-select_camera_primary-container</value>
      <webElementGuid>9f528f81-96a2-467a-969f-2d8bf250d1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7803b2d7-a2ac-4652-999e-0ebadeda4d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1acff104-f076-4b6d-ba25-f5894bb80f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Search --</value>
      <webElementGuid>4c0a0a42-3ea6-4ed2-9bdb-11db94012e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Search --</value>
      <webElementGuid>04573190-77dc-422b-b059-51388736d6cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-select_camera_primary-container&quot;)</value>
      <webElementGuid>456de8a7-3473-48b8-89e7-27d9d0484af3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-select_camera_primary-container']</value>
      <webElementGuid>16d18493-44fc-4e64-ba98-defb1eed0067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/span/span/span/span</value>
      <webElementGuid>11c204d8-468c-4b75-a0d7-1e41429121df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-select_camera_primary-container' and @title = '-- Search --' and (text() = '-- Search --' or . = '-- Search --')]</value>
      <webElementGuid>3753f2a7-9ad4-40b8-b83f-269935e9c751</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
