<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left Camera Selection</name>
   <tag></tag>
   <elementGuidId>105999d9-925f-4af2-b407-5c11abd7aa4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-select_camera_first-container']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-select_camera_first-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3bc71214-af66-485f-a07c-a69820dc871c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>e3808699-4fb4-4a4b-bc55-249a0b2cf769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-select_camera_first-container</value>
      <webElementGuid>e1d0da25-bd5c-412b-9a03-29cccbf8b708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>6773b39f-efe5-4b90-81b0-9fdad035c320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a6e40418-fbda-401e-a4c3-4667f6170a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>-- Search --</value>
      <webElementGuid>7c547d98-5f27-40a2-841b-1f31a34215e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-- Search --</value>
      <webElementGuid>cba48a1a-a8d8-4cfa-9265-0ea9185878d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-select_camera_first-container&quot;)</value>
      <webElementGuid>54bac5d9-b05b-44c0-80a8-1fd132fab341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-select_camera_first-container']</value>
      <webElementGuid>ef2b6302-055a-486f-a8c8-9450962b1752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>57e33754-0ab8-4674-809c-34a062779c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-select_camera_first-container' and @title = '-- Search --' and (text() = '-- Search --' or . = '-- Search --')]</value>
      <webElementGuid>3b86b3c0-fa2b-44c2-8ad3-a529dad2ac35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
