<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left Loading CCTV stream</name>
   <tag></tag>
   <elementGuidId>717ef169-4606-4131-831e-bfe90ad207fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stream_first']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;stream_first&quot;)[count(. | //canvas[@id = 'stream_first' and @width = '100%']) = count(//canvas[@id = 'stream_first' and @width = '100%'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream_first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>43284493-b3c7-4b63-90c9-e610e17434a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream_first</value>
      <webElementGuid>c018d7e4-4a0b-4b49-a24c-e33e8957d7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8ad9a1d5-b8d5-4067-a252-4fe0c058eaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream_first&quot;)</value>
      <webElementGuid>561b98d8-a5eb-40c3-913a-ddd6f8ce3412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stream_first']</value>
      <webElementGuid>b92d358a-f528-43ad-8b22-5af484726541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_stream_first']/canvas</value>
      <webElementGuid>4fe2d721-e674-43f6-92f5-851011ee2a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>7949ca3a-4d46-44c7-a716-ae77dac33b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stream_first']</value>
      <webElementGuid>1effdf24-c361-41ef-a121-34c3839216af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
