<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left Camera Playing</name>
   <tag></tag>
   <elementGuidId>014f6fd9-6a06-4149-9e83-7ba2a6f6ac39</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stream_first']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;stream_first&quot;)[count(. | //canvas[@id = 'stream_first' and @width = '1920' and @height = '1080']) = count(//canvas[@id = 'stream_first' and @width = '1920' and @height = '1080'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream_first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>08c38a30-2b06-4a4e-ad9f-daba464ef600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream_first</value>
      <webElementGuid>c74dc00b-08b1-4863-821b-1e4cccd9bde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>b5c97be1-5e42-4d51-b873-2da5cefd91cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>ec91ddb7-2649-449d-84ed-18ae01cf87d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream_first&quot;)</value>
      <webElementGuid>fe7f11ad-f360-4f8a-8c91-9c48f9ace200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stream_first']</value>
      <webElementGuid>33c4f40a-7884-41a3-93f3-135b8c550a9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_stream_first']/canvas</value>
      <webElementGuid>9cc10d12-7015-46c4-bf56-b5c8f43bd0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>8d437396-d712-493b-8bbf-b0646afe6b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stream_first']</value>
      <webElementGuid>a0ea8b59-2c96-444a-8f1b-292e5bc5cc2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
