<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left Search Identity</name>
   <tag></tag>
   <elementGuidId>70a96f97-01bb-46c8-af77-0d377b69c2cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='snapshotIdentify_first']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#snapshotIdentify_first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>539a3aff-fd7e-4853-8e9e-4e89340e6b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4749e7be-0882-475f-8142-6eefdde08cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>snapshotIdentify_first</value>
      <webElementGuid>f3486fc4-1d94-42d1-a9e4-9124698d94f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>17a2485d-50a0-4acc-b24e-31fa7f6694fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>b7ea7f68-bccd-4c7e-99cb-d645808f4f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>d6a24610-0049-4ac0-83c2-b2a183385ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search Identity</value>
      <webElementGuid>f9995118-dc11-4f36-b306-0df66ca48dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;snapshotIdentify_first&quot;)</value>
      <webElementGuid>d4d01d4a-1615-46e6-b217-856da5cfe9b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='snapshotIdentify_first']</value>
      <webElementGuid>ae275336-a911-4955-8785-a09d71242868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>65446aca-9d06-4f94-8f2f-ed8530e828a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'snapshotIdentify_first' and (text() = 'Search Identity' or . = 'Search Identity')]</value>
      <webElementGuid>e3192c53-da3c-48b0-b005-e3a27a9b2488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
