<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Right Camera Playing</name>
   <tag></tag>
   <elementGuidId>0e5f1a55-ee39-4e97-ae72-de6905f92eb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stream_secondary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream_secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>754845bf-c276-4489-9c47-f64715cefb1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream_secondary</value>
      <webElementGuid>eef8b4df-4635-48de-b7c3-7a8fa4526b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1920</value>
      <webElementGuid>2e9f58a6-d076-4be9-8f93-fb7acf7acd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>bfde03b7-bcf0-467e-93c1-a3fb045ff560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream_secondary&quot;)</value>
      <webElementGuid>001f833a-77ae-4a7e-8696-f061987170ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stream_secondary']</value>
      <webElementGuid>d215241f-2aaa-4994-8719-356f067e7074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_stream_secondary']/canvas</value>
      <webElementGuid>0a3bfc7c-cad3-4ab9-93f3-7f826426e77f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>3ec99896-06d5-4f21-af6a-38aa3a8da173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stream_secondary']</value>
      <webElementGuid>b85984ea-44e4-47bc-8390-b9406b4fa3f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
