<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Right Loading CCTV Stream</name>
   <tag></tag>
   <elementGuidId>73d4d733-eeb2-42dc-a801-6f7e1b3c01c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='stream_secondary']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;stream_secondary&quot;)[count(. | //canvas[@id = 'stream_secondary' and @width = '100%']) = count(//canvas[@id = 'stream_secondary' and @width = '100%'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#stream_secondary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>8105dc10-a2c4-4f05-ae2d-71669d9aaac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stream_secondary</value>
      <webElementGuid>eaa2e91c-741d-4dee-97b8-13ef9336fb46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b581eec2-7226-430e-9d0a-a0c0a00c839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stream_secondary&quot;)</value>
      <webElementGuid>05c5e774-6e7c-41dd-a7ce-2a2a11b48f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='stream_secondary']</value>
      <webElementGuid>83d6475a-0cef-43bf-a532-8ff6c7a5fb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='show_stream_secondary']/canvas</value>
      <webElementGuid>b4f38601-dc5e-4edb-ad73-45bce60e3917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>f58849d9-8f05-4b87-b94a-d65a291c2e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'stream_secondary']</value>
      <webElementGuid>c3da50d3-349d-4fce-bdf8-aad80e54e84d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
