<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete Pop Up</name>
   <tag></tag>
   <elementGuidId>f5fdb99c-368b-4ad1-8f99-e183bb6493f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='id_modal_delete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_modal_delete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9403f5f7-5c40-42f8-ab14-2a3dae0500a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_modal_delete</value>
      <webElementGuid>789c0b02-6e77-419a-b14e-2ec9b9285d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn bg-gradient-danger</value>
      <webElementGuid>f5d4a23f-a28f-4250-8cd5-f7e17e5fbb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/roles/delete/65aa32f712ca78ff5335bf4c</value>
      <webElementGuid>146b4ba7-5866-4bd9-a264-79b0e5f76465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>74bcd76a-ab6f-4167-a650-a57652979f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_modal_delete&quot;)</value>
      <webElementGuid>85b30d5e-a314-4030-999f-d39b84b77232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='id_modal_delete']</value>
      <webElementGuid>d664197f-02c9-46ac-a612-e692ccff62b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteModal']/div/div/div[3]/a</value>
      <webElementGuid>69342d0a-f6b5-47f8-a3f4-ff4955135256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete')]</value>
      <webElementGuid>d56fdd8e-170c-4118-ba95-a26384100ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/roles/delete/65aa32f712ca78ff5335bf4c')]</value>
      <webElementGuid>4588beac-61a8-49a0-9c61-c16e61a0a33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>39c7287c-b501-409e-84a3-f389cecca13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'id_modal_delete' and @href = '/roles/delete/65aa32f712ca78ff5335bf4c' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>78215f8e-777b-4d49-bd6c-769f0495944f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
