<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete Button pop up</name>
   <tag></tag>
   <elementGuidId>d54d71c1-349e-40f7-b46a-ea83dc97b0cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_modal_delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='id_modal_delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3dd98406-0182-4ad1-a480-a9eaecf47412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_modal_delete</value>
      <webElementGuid>f7952b15-ead1-481f-b9d2-435f3b70c397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn bg-gradient-danger</value>
      <webElementGuid>6b76bcad-f34e-46d5-ba21-18e556133a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/accounts/delete/651bc53e8efcf778865e88c0</value>
      <webElementGuid>6ec274a6-2208-430f-a328-9d297ab14ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>2a80b75b-8f28-4dfa-8ac7-04fbd49bafa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_modal_delete&quot;)</value>
      <webElementGuid>3408cfe8-2374-4119-8908-db2f30f2f04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='id_modal_delete']</value>
      <webElementGuid>99af181d-6d58-49a4-b13a-b0975163d1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='deleteModal']/div/div/div[3]/a</value>
      <webElementGuid>86abffe5-04ef-4f04-ad0f-e0046d4dfd53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Delete')]</value>
      <webElementGuid>5436c351-76ce-4fc6-8aa9-e41e621437c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/accounts/delete/651bc53e8efcf778865e88c0')]</value>
      <webElementGuid>551b6079-110c-4e9c-9141-c3c76f47f3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>be9143f7-12e1-4119-9851-9cb3c9edc6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'id_modal_delete' and @href = '/accounts/delete/651bc53e8efcf778865e88c0' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>6f84aaa6-ba09-4ba0-859d-72f4dee170c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
