<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_gm-style-iw-tc</name>
   <tag></tag>
   <elementGuidId>36f044f1-1af5-4c89-9b6d-3a4827c73bf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='map']/div/div[3]/div/div[2]/div/div[4]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.gm-style-iw-tc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>915212e1-e00c-47cd-8cd8-ed95272930e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gm-style-iw-tc</value>
      <webElementGuid>82265302-0d71-49b3-bd80-6f18de46bae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;map&quot;)/div[1]/div[@class=&quot;gm-style&quot;]/div[1]/div[2]/div[1]/div[4]/div[1]/div[@class=&quot;gm-style-iw-a&quot;]/div[@class=&quot;gm-style-iw-t&quot;]/div[@class=&quot;gm-style-iw-tc&quot;]</value>
      <webElementGuid>dbcb77e8-5730-47df-b927-3de354802d8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='map']/div/div[3]/div/div[2]/div/div[4]/div/div/div/div[2]</value>
      <webElementGuid>09319401-db31-4659-a135-d5554a603e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div[2]</value>
      <webElementGuid>ab5d7983-654b-42d8-9dbc-64574003fdf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
